name = "ad-api"
compatibility_date = "2024-08-24"
compatibility_flags = ["nodejs_compat"]


routes = [
  { pattern = "portal-local.aiya.me/api/ads/*", zone_name = "aiya.me" },
  { pattern = "lambda-api.aiya.me/api/ads/*", zone_name = "aiya.me" },
  { pattern = "portal-dev.aiya.me/api/ads/*", zone_name = "aiya.me" },
  { pattern = "portal.aiya.me/api/ads/*", zone_name = "aiya.me" },
]

[placement]
mode = "smart"

[[queues.producers]]
binding = "AD_ACCOUNT_SYNC"
queue = "ad-account-sync"

[[queues.producers]]
binding = "AD_CAMPAIGN_SYNC"
queue = "ad-campaign-sync"

[[queues.producers]]
binding = "AD_SETS_SYNC"
queue = "ad-sets-sync"

[[queues.producers]]
binding = "AD_ADS_SYNC"
queue = "ad-ads-sync"

[[queues.producers]]
binding = "AD_CAMPAIGN_SYNC_START"
queue = "ad-campaign-sync-start"

[[queues.producers]]
binding = "AD_CAMPAIGN_SYNC_PROCESS"
queue = "ad-campaign-sync-process"

[[queues.producers]]
binding = "AD_CAMPAIGN_SYNC_PROCESS_ADSET"
queue = "ad-campaign-sync-process-adset"

[[queues.producers]]
binding = "AD_CAMPAIGN_SYNC_PROCESS_ADSET_ADS"
queue = "ad-campaign-sync-process-adset-ads"


[[queues.consumers]]
queue = "ad-account-sync"
max_batch_size = 1               # optional: defaults to 10
max_batch_timeout = 5           # optional: defaults to 5 seconds
max_concurrency = 6

[[queues.consumers]]
queue = "ad-campaign-sync"
max_batch_size = 10                 # optional: defaults to 10
max_batch_timeout = 5              # optional: defaults to 5 seconds
max_concurrency = 5
max_retries = 3

[[queues.consumers]]
queue = "ad-sets-sync"
max_batch_size = 10                 # optional: defaults to 10
max_batch_timeout = 5              # optional: defaults to 5 seconds
max_concurrency = 5
max_retries = 3

[[queues.consumers]]
queue = "ad-ads-sync"
max_batch_size = 10                 # optional: defaults to 10
max_batch_timeout = 5              # optional: defaults to 5 seconds
max_concurrency = 5
max_retries = 3

[[queues.consumers]]
queue = "ad-campaign-sync-start"
max_batch_size = 1               # optional: defaults to 10
max_batch_timeout = 15           # optional: defaults to 5 seconds


[[queues.consumers]]
queue = "ad-campaign-sync-process"
max_batch_size = 1                 # optional: defaults to 10
max_batch_timeout = 5              # optional: defaults to 5 seconds
max_concurrency = 20
max_retries = 3

[[queues.consumers]]
queue = "ad-campaign-sync-process-adset"
max_batch_size = 1                       # optional: defaults to 10
max_batch_timeout = 5                    # optional: defaults to 5 seconds
max_concurrency = 20
max_retries = 3

[[queues.consumers]]
queue = "ad-campaign-sync-process-adset-ads"
max_batch_size = 1                           # optional: defaults to 10
max_batch_timeout = 5                        # optional: defaults to 5 seconds
max_concurrency = 20
max_retries = 3

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
