// Generated by Wrangler on Thu Jan 16 2025 03:02:56 GMT+0700 (GMT+07:00)
// by running `wrangler types app/types/worker-configuration.d.ts --env-interface WorkerEnv`

interface WorkerEnv {
	DIRECTUS_URL: "https://console.portal.aiya.ai";
	PORTAL_URL: "https://portal.aiya.me";
}
