// Generated by Wrangler on Thu Sep 05 2024 23:14:27 GMT+0700 (Indochina Time)
// by running `wrangler types`

interface Env {
	NODE_ENV: string;
	PORT: string;
	LAMBDA_SECRET_KEY: string;
	DIRECTUS_URL: string;
	DIRECTUS_SECRET_KEY: string;
	DIRECTUS_SERVICE_TOKEN: string;
	PORTAL_URL: string;
	FB_APP_ID: string;
	FB_APP_SECRET: string;
	FB_APP_LOGIN_ID: string;
	SENTENCE_EMBEDINGS_QUEUE: Queue;
	VECTOR_SENTENCES: VectorizeIndex;
}
