name = "bot-api_dev"
compatibility_date = "2024-08-21"
compatibility_flags = ["nodejs_compat"]

routes = [
  # { pattern = "lambda-api-local.aiya.me/api/bots/*", zone_name = "aiya.me" },
  { pattern = "portal-dev.aiya.me/api/bots/*", zone_name = "aiya.me" },
  { pattern = "lambda-api-dev.aiya.me/api/bots/*", zone_name = "aiya.me" },
]

services = [{ binding = "BillingService", service = "billing-api_dev" }]

[placement]
mode = "smart"

[vars]
DIRECTUS_URL = "https://console.portal.aiya.ai"
SUPABASE_URL = "https://app-api.aiya.ai"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhibHhpaHZjbnNrdHdqaWNzeXJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTMzMjg0ODksImV4cCI6MjAwODkwNDQ4OX0.MElXtyFRyjfyMlCNyqdf-iAI7xpPk0dCrzxH9Qe2RVY"


# [[vectorize]]
# binding = "VECTOR_SENTENCES"
# index_name = "sentences_embeddings"

[[queues.producers]]
binding = "SENTENCE_EMBEDINGS_QUEUE"
queue = "sentences-embeddings"

[[queues.consumers]]
queue = "sentences-embeddings"
max_batch_size = 10            # optional: defaults to 10
max_batch_timeout = 3          # optional: defaults to 5 seconds

[[queues.producers]]
binding = "CAPI_QUEUE"
queue = "capi-queue"

[[queues.consumers]]
queue = "capi-queue"
max_batch_size = 10   # optional: defaults to 10
max_batch_timeout = 5 # optional: defaults to 5 seconds


[[kv_namespaces]]
binding = "CACHING"
id = "b494201ff6b74231a02c94891f805ba7"

[env.prod]
name = "bot-api_prod"

routes = [
  { pattern = "portal.aiya.me/api/bots/*", zone_name = "aiya.me" },
  { pattern = "portal.aiya.me/api/aws/*", zone_name = "aiya.me" },
  { pattern = "lambda-api.aiya.me/api/bots/*", zone_name = "aiya.me" },
]

[env.prod.vars]
DIRECTUS_URL = "https://console.portal.aiya.ai"
SUPABASE_URL = "https://app-api.aiya.ai"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhibHhpaHZjbnNrdHdqaWNzeXJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTMzMjg0ODksImV4cCI6MjAwODkwNDQ4OX0.MElXtyFRyjfyMlCNyqdf-iAI7xpPk0dCrzxH9Qe2RVY"

[env.prod.placement]
mode = "smart"

# [[env.prod.vectorize]]
# binding = "VECTOR_SENTENCES"
# index_name = "sentences_embeddings"

[[env.prod.queues.producers]]
binding = "SENTENCE_EMBEDINGS_QUEUE"
queue = "sentences-embeddings_prod"

[[env.prod.queues.consumers]]
queue = "sentences-embeddings_prod"
max_batch_size = 10                 # optional: defaults to 10
max_batch_timeout = 3               # optional: defaults to 5 seconds


[[env.prod.queues.producers]]
binding = "CAPI_QUEUE"
queue = "capi-queue_prod"

[[env.prod.queues.consumers]]
queue = "capi-queue_prod"
max_batch_size = 10       # optional: defaults to 10
max_batch_timeout = 5     # optional: defaults to 5 seconds


[[env.prod.queues.producers]]
binding = "BILLING_QUEUE"
queue = "billing-queue_prod"

[[env.prod.queues.consumers]]
queue = "billing-queue_prod"
max_batch_size = 10          # optional: defaults to 10
max_batch_timeout = 5        # optional: defaults to 5 seconds


[[env.prod.kv_namespaces]]
binding = "CACHING"
id = "b494201ff6b74231a02c94891f805ba7"
