name = "pubsub-api-dev"
main = "src/index.ts"
compatibility_date = "2024-12-30"

[placement]
mode = "smart"

[vars]
PUBSUB_PROJECT_ID = "aiya-x" # Replace with your GCP Project ID
PUBSUB_CREDENTIALS = ''
