const saas_subscriptionsCollection = {
  collection: "saas_subscriptions",
  meta: {
    collection: "saas_subscriptions",
    icon: "card_membership",
    note: "User subscription information",
    display_template: "{{user_id.first_name}} - {{plan_type}}",
    hidden: false,
    singleton: false,
    translations: [
      {
        language: "en-US",
        translation: "Subscriptions",
      },
      {
        language: "th-TH",
        translation: "การสมัครสมาชิก",
      },
    ],
    sort: 1,
  },
  schema: {
    name: "saas_subscriptions",
    comment: "Stores subscription data from Stripe",
  },
  fields: [
    {
      collection: "saas_subscriptions",
      field: "id",
      type: "uuid",
      meta: {
        collection: "saas_subscriptions",
        field: "id",
        special: ["uuid"],
        interface: "input",
        readonly: true,
        hidden: true,
        width: "full",
        sort: 1,
        required: false,
      },
      schema: {
        name: "id",
        table: "saas_subscriptions",
        data_type: "uuid",
        default_value: null,
        generation_expression: null,
        max_length: null,
        numeric_precision: null,
        numeric_scale: null,
        is_generated: true,
        is_nullable: false,
        is_unique: true,
        is_primary_key: true,
        has_auto_increment: false,
        is_indexed: false,
        foreign_key_schema: null,
        foreign_key_table: null,
        foreign_key_column: null,
        comment: null,
      },
    },
    {
      collection: "saas_subscriptions",
      field: "user_created",
      type: "uuid",
      schema: {
        name: "user_created",
        table: "saas_subscriptions",
        data_type: "uuid",
        default_value: null,
        generation_expression: null,
        max_length: null,
        numeric_precision: null,
        numeric_scale: null,
        is_generated: false,
        is_nullable: true,
        is_unique: false,
        is_indexed: false,
        is_primary_key: false,
        has_auto_increment: false,
        foreign_key_schema: "public",
        foreign_key_table: "directus_users",
        foreign_key_column: "id",
        comment: null,
      },
      meta: {
        collection: "saas_subscriptions",
        field: "user_created",
        special: ["user-created"],
        interface: "select-dropdown-m2o",
        options: {
          template: "{{avatar}} {{first_name}} {{last_name}}",
        },
        display: "user",
        display_options: null,
        readonly: true,
        hidden: true,
        sort: 2,
        width: "half",
        translations: null,
        note: null,
        conditions: null,
        required: false,
        group: null,
        validation: null,
        validation_message: null,
      },
    },
    {
      collection: "saas_subscriptions",
      field: "date_created",
      type: "timestamp",
      schema: {
        name: "date_created",
        table: "saas_subscriptions",
        data_type: "timestamp with time zone",
        default_value: null,
        generation_expression: null,
        max_length: null,
        numeric_precision: null,
        numeric_scale: null,
        is_generated: false,
        is_nullable: true,
        is_unique: false,
        is_indexed: false,
        is_primary_key: false,
        has_auto_increment: false,
        foreign_key_schema: null,
        foreign_key_table: null,
        foreign_key_column: null,
        comment: null,
      },
      meta: {
        collection: "saas_subscriptions",
        field: "date_created",
        special: ["date-created"],
        interface: "datetime",
        options: null,
        display: "datetime",
        display_options: {
          relative: true,
        },
        readonly: true,
        hidden: true,
        sort: 3,
        width: "half",
        translations: null,
        note: null,
        conditions: null,
        required: false,
        group: null,
        validation: null,
        validation_message: null,
      },
    },
    {
      collection: "saas_subscriptions",
      field: "user_updated",
      type: "uuid",
      schema: {
        name: "user_updated",
        table: "saas_subscriptions",
        data_type: "uuid",
        default_value: null,
        generation_expression: null,
        max_length: null,
        numeric_precision: null,
        numeric_scale: null,
        is_generated: false,
        is_nullable: true,
        is_unique: false,
        is_indexed: false,
        is_primary_key: false,
        has_auto_increment: false,
        foreign_key_schema: "public",
        foreign_key_table: "directus_users",
        foreign_key_column: "id",
        comment: null,
      },
      meta: {
        collection: "saas_subscriptions",
        field: "user_updated",
        special: ["user-updated"],
        interface: "select-dropdown-m2o",
        options: {
          template: "{{avatar}} {{first_name}} {{last_name}}",
        },
        display: "user",
        display_options: null,
        readonly: true,
        hidden: true,
        sort: 4,
        width: "half",
        translations: null,
        note: null,
        conditions: null,
        required: false,
        group: null,
        validation: null,
        validation_message: null,
      },
    },
    {
      collection: "saas_subscriptions",
      field: "date_updated",
      type: "timestamp",
      schema: {
        name: "date_updated",
        table: "saas_subscriptions",
        data_type: "timestamp with time zone",
        default_value: null,
        generation_expression: null,
        max_length: null,
        numeric_precision: null,
        numeric_scale: null,
        is_generated: false,
        is_nullable: true,
        is_unique: false,
        is_indexed: false,
        is_primary_key: false,
        has_auto_increment: false,
        foreign_key_schema: null,
        foreign_key_table: null,
        foreign_key_column: null,
        comment: null,
      },
      meta: {
        collection: "saas_subscriptions",
        field: "date_updated",
        special: ["date-updated"],
        interface: "datetime",
        options: null,
        display: "datetime",
        display_options: {
          relative: true,
        },
        readonly: true,
        hidden: true,
        sort: 5,
        width: "half",
        translations: null,
        note: null,
        conditions: null,
        required: false,
        group: null,
        validation: null,
        validation_message: null,
      },
    },
    {
      collection: "saas_subscriptions",
      field: "user_id",
      type: "uuid",
      schema: {
        name: "user_id",
        table: "saas_subscriptions",
        data_type: "uuid",
        default_value: null,
        generation_expression: null,
        max_length: null,
        numeric_precision: null,
        numeric_scale: null,
        is_generated: false,
        is_nullable: true,
        is_unique: false,
        is_indexed: false,
        is_primary_key: false,
        has_auto_increment: false,
        foreign_key_schema: "public",
        foreign_key_table: "directus_users",
        foreign_key_column: "id",
        comment: null,
      },
      meta: {
        collection: "saas_subscriptions",
        field: "user_id",
        special: ["m2o"],
        interface: "select-dropdown-m2o",
        options: {
          template: "{{first_name}} {{last_name}}",
        },
        display: null,
        display_options: null,
        readonly: false,
        hidden: false,
        sort: 6,
        width: "full",
        translations: null,
        note: null,
        conditions: null,
        required: false,
        group: null,
        validation: null,
        validation_message: null,
      },
    },
    {
      collection: "saas_subscriptions",
      field: "stripe_subscription_id",
      type: "string",
      meta: {
        collection: "saas_subscriptions",
        field: "stripe_subscription_id",
        special: null,
        interface: "input",
        options: null,
        display: null,
        display_options: null,
        readonly: false,
        hidden: false,
        sort: 7,
        width: "full",
        required: true,
        note: "Stripe subscription reference",
      },
      schema: {
        name: "stripe_subscription_id",
        table: "saas_subscriptions",
        data_type: "character varying",
        default_value: null,
        max_length: 255,
        is_nullable: false,
      },
    },
    {
      collection: "saas_subscriptions",
      field: "stripe_price_id",
      type: "string",
      meta: {
        collection: "saas_subscriptions",
        field: "stripe_price_id",
        special: null,
        interface: "input",
        options: null,
        readonly: false,
        hidden: false,
        sort: 8,
        width: "full",
        required: true,
        note: "Stripe price reference",
      },
      schema: {
        name: "stripe_price_id",
        table: "saas_subscriptions",
        data_type: "character varying",
        default_value: null,
        max_length: 255,
        is_nullable: false,
      },
    },
    {
      collection: "saas_subscriptions",
      field: "stripe_product_id",
      type: "string",
      meta: {
        collection: "saas_subscriptions",
        field: "stripe_product_id",
        special: null,
        interface: "input",
        options: null,
        readonly: false,
        hidden: false,
        sort: 9,
        width: "full",
        required: true,
        note: "Stripe product reference",
      },
      schema: {
        name: "stripe_product_id",
        table: "saas_subscriptions",
        data_type: "character varying",
        default_value: null,
        max_length: 255,
        is_nullable: false,
      },
    },
    {
      collection: "saas_subscriptions",
      field: "plan_type",
      type: "string",
      meta: {
        collection: "saas_subscriptions",
        field: "plan_type",
        special: null,
        interface: "select-dropdown",
        options: {
          choices: [
            { text: "Free", value: "free" },
            { text: "Starter", value: "starter" },
            { text: "Growth", value: "growth" },
          ],
        },
        display: null,
        display_options: null,
        readonly: false,
        hidden: false,
        sort: 10,
        width: "full",
        required: true,
      },
      schema: {
        name: "plan_type",
        table: "saas_subscriptions",
        data_type: "character varying",
        default_value: "free",
        max_length: 50,
        is_nullable: false,
      },
    },
    {
      collection: "saas_subscriptions",
      field: "amount",
      type: "decimal",
      meta: {
        collection: "saas_subscriptions",
        field: "amount",
        special: null,
        interface: "input",
        options: {
          min: 0,
        },
        readonly: false,
        hidden: false,
        sort: 11,
        width: "half",
        required: true,
      },
      schema: {
        name: "amount",
        table: "saas_subscriptions",
        data_type: "numeric",
        numeric_precision: 10,
        numeric_scale: 2,
        is_nullable: false,
      },
    },
    {
      collection: "saas_subscriptions",
      field: "currency",
      type: "string",
      meta: {
        collection: "saas_subscriptions",
        field: "currency",
        special: null,
        interface: "input",
        options: null,
        readonly: false,
        hidden: false,
        sort: 12,
        width: "half",
        required: true,
      },
      schema: {
        name: "currency",
        table: "saas_subscriptions",
        data_type: "character varying",
        default_value: "thb",
        max_length: 3,
        is_nullable: false,
      },
    },
    {
      collection: "saas_subscriptions",
      field: "status",
      type: "string",
      meta: {
        collection: "saas_subscriptions",
        field: "status",
        special: null,
        interface: "select-dropdown",
        options: {
          choices: [
            { text: "Trialing", value: "trialing" },
            { text: "Active", value: "active" },
            { text: "Past Due", value: "past_due" },
            { text: "Canceled", value: "canceled" },
            { text: "Incomplete", value: "incomplete" },
            { text: "Incomplete Expired", value: "incomplete_expired" },
          ],
        },
        display: null,
        display_options: null,
        readonly: false,
        hidden: false,
        sort: 13,
        width: "full",
        required: true,
      },
      schema: {
        name: "status",
        table: "saas_subscriptions",
        data_type: "character varying",
        default_value: "incomplete",
        max_length: 50,
        is_nullable: false,
      },
    },
    {
      collection: "saas_subscriptions",
      field: "collection_method",
      type: "string",
      meta: {
        collection: "saas_subscriptions",
        field: "collection_method",
        special: null,
        interface: "select-dropdown",
        options: {
          choices: [
            { text: "Charge Automatically", value: "charge_automatically" },
            { text: "Send Invoice", value: "send_invoice" },
          ],
        },
        readonly: false,
        hidden: false,
        sort: 14,
        width: "full",
        required: true,
      },
      schema: {
        name: "collection_method",
        table: "saas_subscriptions",
        data_type: "character varying",
        default_value: "charge_automatically",
        max_length: 50,
        is_nullable: false,
      },
    },
    {
      collection: "saas_subscriptions",
      field: "trial_start",
      type: "timestamp",
      meta: {
        collection: "saas_subscriptions",
        field: "trial_start",
        special: null,
        interface: "datetime",
        readonly: false,
        hidden: false,
        sort: 15,
        width: "half",
        required: false,
        note: "Trial period start date",
      },
      schema: {
        name: "trial_start",
        table: "saas_subscriptions",
        data_type: "timestamp with time zone",
        is_nullable: true,
      },
    },
    {
      collection: "saas_subscriptions",
      field: "trial_end",
      type: "timestamp",
      meta: {
        collection: "saas_subscriptions",
        field: "trial_end",
        special: null,
        interface: "datetime",
        readonly: false,
        hidden: false,
        sort: 16,
        width: "half",
        required: false,
        note: "Trial period end date",
      },
      schema: {
        name: "trial_end",
        table: "saas_subscriptions",
        data_type: "timestamp with time zone",
        is_nullable: true,
      },
    },
    {
      collection: "saas_subscriptions",
      field: "billing_cycle_anchor",
      type: "timestamp",
      meta: {
        collection: "saas_subscriptions",
        field: "billing_cycle_anchor",
        special: null,
        interface: "datetime",
        readonly: false,
        hidden: false,
        sort: 17,
        width: "full",
        required: true,
        note: "Next billing cycle start date",
      },
      schema: {
        name: "billing_cycle_anchor",
        table: "saas_subscriptions",
        data_type: "timestamp with time zone",
        is_nullable: false,
      },
    },
    {
      collection: "saas_subscriptions",
      field: "current_period_start",
      type: "timestamp",
      meta: {
        collection: "saas_subscriptions",
        field: "current_period_start",
        special: null,
        interface: "datetime",
        readonly: false,
        hidden: false,
        sort: 18,
        width: "half",
        required: true,
        note: "Current billing period start date",
      },
      schema: {
        name: "current_period_start",
        table: "saas_subscriptions",
        data_type: "timestamp with time zone",
        is_nullable: false,
      },
    },
    {
      collection: "saas_subscriptions",
      field: "current_period_end",
      type: "timestamp",
      meta: {
        collection: "saas_subscriptions",
        field: "current_period_end",
        special: null,
        interface: "datetime",
        readonly: false,
        hidden: false,
        sort: 19,
        width: "half",
        required: true,
        note: "Current billing period end date",
      },
      schema: {
        name: "current_period_end",
        table: "saas_subscriptions",
        data_type: "timestamp with time zone",
        is_nullable: false,
      },
    },
    {
      collection: "saas_subscriptions",
      field: "cancel_at_period_end",
      type: "boolean",
      meta: {
        collection: "saas_subscriptions",
        field: "cancel_at_period_end",
        special: null,
        interface: "boolean",
        readonly: false,
        hidden: false,
        sort: 20,
        width: "full",
        required: true,
        note: "Whether subscription will be canceled at period end",
      },
      schema: {
        name: "cancel_at_period_end",
        table: "saas_subscriptions",
        data_type: "boolean",
        default_value: false,
        is_nullable: false,
      },
    },
    {
      collection: "saas_subscriptions",
      field: "canceled_at",
      type: "timestamp",
      meta: {
        collection: "saas_subscriptions",
        field: "canceled_at",
        special: null,
        interface: "datetime",
        readonly: false,
        hidden: false,
        sort: 21,
        width: "full",
        required: false,
        note: "Cancellation date",
      },
      schema: {
        name: "canceled_at",
        table: "saas_subscriptions",
        data_type: "timestamp with time zone",
        is_nullable: true,
      },
    },
    {
      collection: "saas_subscriptions",
      field: "metadata",
      type: "json",
      meta: {
        collection: "saas_subscriptions",
        field: "metadata",
        special: null,
        interface: "input-code",
        options: {
          language: "json",
        },
        readonly: false,
        hidden: false,
        sort: 22,
        width: "full",
        required: false,
        note: "Additional subscription metadata",
      },
      schema: {
        name: "metadata",
        table: "saas_subscriptions",
        data_type: "jsonb",
        is_nullable: true,
      },
    },
  ],
};

// Relationship definitions
const saas_subscriptionsUserFieldRelationship = {
  collection: "saas_subscriptions",
  field: "user_id",
  related_collection: "directus_users",
  meta: { sort_field: null },
  schema: { on_delete: "SET NULL" },
};

export { saas_subscriptionsCollection, saas_subscriptionsUserFieldRelationship };
