// Generated by Wrangler on Tue Aug 13 2024 00:49:09 GMT+0700 (Indochina Time)
// by running `wrangler types`

interface Env {
	DIRECTUS_URL: "https://console.portal.aiya.ai";
	DIRECTUS_SECRET_KEY: "m2yl32fbitsijm8bso37mlhvi603eqz3";
	DIRECTUS_SERVICE_TOKEN: "f8LiIZVxY2-jGDqgeTU40IZ2xrj-7ygy";
}
