name = "webhook-line-v2_dev"
compatibility_date = "2024-08-12"

routes = [
  { pattern = "webhook-dev.aiya.me/api/v2/line", zone_id = "46fe6c128f87451e7bc42c74c0a47169" },
  { pattern = "webhook-dev.aiya.me/api/v2/line/*", zone_id = "46fe6c128f87451e7bc42c74c0a47169" },
]

services = [{ binding = "WORKER_CHANNEL", service = "channel-api_dev" }]


[placement]
mode = "smart"

[vars]
# AWS_ACCESS_KEY_ID = ""
# AWS_SECRET_ACCESS_KEY = ""
AWS_REGION = "ap-northeast-1"
SNS_TOPIC_ARN = "arn:aws:sns:ap-northeast-1:398684454127:webhook-line-sns-v2_dev.fifo"
DIRECTUS_URL = "https://console.portal.aiya.ai"

[[d1_databases]]
binding = "DB"
database_name = "webhooks_dev"
database_id = "a8c89931-6fdb-450a-8015-c7a2a6fd4926"

[[kv_namespaces]]
binding = "KV_PORTAL"
id = "a254b6e667cd4e64a038493398ce998e"

[env.prod]
name = "webhook-line-v2_prod"

routes = [
  { pattern = "webhook.aiya.me/api/v2/line", zone_id = "46fe6c128f87451e7bc42c74c0a47169" },
  { pattern = "webhook.aiya.me/api/v2/line/*", zone_id = "46fe6c128f87451e7bc42c74c0a47169" },
]

services = [{ binding = "WORKER_CHANNEL", service = "channel-api_prod" }]

[[env.prod.d1_databases]]
binding = "DB"
database_name = "webhooks"
database_id = "48e858e8-8353-490a-b86e-edf209b237b6"

[env.prod.vars]
# AWS_ACCESS_KEY_ID = ""
# AWS_SECRET_ACCESS_KEY = ""
AWS_REGION = "ap-northeast-1"
SNS_TOPIC_ARN = "arn:aws:sns:ap-northeast-1:398684454127:webhook-line-sns-v2_prod.fifo"
DIRECTUS_URL = "https://console.portal.aiya.ai"

[[env.prod.kv_namespaces]]
binding = "KV_PORTAL"
id = "fe0b7a47778942d69ce767ca149d1cad"


# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
