name = "facebook-proxy"
compatibility_date = "2024-08-24"
compatibility_flags = ["nodejs_compat"]


routes = [
  { pattern = "portal-local.aiya.me/api/ads/*", zone_name = "aiya.me" },
  { pattern = "lambda-api.aiya.me/api/ads/*", zone_name = "aiya.me" },
  { pattern = "portal-dev.aiya.me/api/ads/*", zone_name = "aiya.me" },
]

[placement]
mode = "smart"

[vars]
PORTAL_URL = "https://portal-dev.aiya.me"
FB_API_URL = "https://graph.facebook.com/v20.0"
FB_APP_ID = "788582819272015"
FB_APP_LOGIN_ID = "764646715708204"

[[queues.producers]]
binding = "AD_ACCOUNT_SYNC"
queue = "ad-account-sync-dev"

[[queues.producers]]
binding = "AD_CAMPAIGN_SYNC"
queue = "ad-campaign-sync-dev"

[[queues.producers]]
binding = "AD_SETS_SYNC"
queue = "ad-sets-sync-dev"

[[queues.producers]]
binding = "AD_ADS_SYNC"
queue = "ad-ads-sync-dev"


[[queues.consumers]]
queue = "ad-account-sync-dev"
max_batch_size = 1            # optional: defaults to 10
max_batch_timeout = 5         # optional: defaults to 5 seconds
max_concurrency = 6

[[queues.consumers]]
queue = "ad-campaign-sync-dev"
max_batch_size = 10            # optional: defaults to 10
max_batch_timeout = 5          # optional: defaults to 5 seconds
max_concurrency = 5
max_retries = 3

[[queues.consumers]]
queue = "ad-sets-sync-dev"
max_batch_size = 10        # optional: defaults to 10
max_batch_timeout = 5      # optional: defaults to 5 seconds
max_concurrency = 5
max_retries = 3

[[queues.consumers]]
queue = "ad-ads-sync-dev"
max_batch_size = 10       # optional: defaults to 10
max_batch_timeout = 5     # optional: defaults to 5 seconds
max_concurrency = 5
max_retries = 3


[env.prod]
name = "ad-api_prod"

routes = [
  { pattern = "portal.aiya.me/api/ads/*", zone_name = "aiya.me" },
  { pattern = "portal.aiya.me/api/adaccounts/*", zone_name = "aiya.me" },
]

[env.prod.placement]
mode = "smart"

[env.prod.vars]
PORTAL_URL = "https://portal.aiya.me"
FB_API_URL = "https://graph.facebook.com/v20.0"
FB_APP_ID = "788582819272015"
FB_APP_LOGIN_ID = "764646715708204"


[[env.prod.queues.producers]]
binding = "AD_ACCOUNT_SYNC"
queue = "ad-account-sync"

[[env.prod.queues.producers]]
binding = "AD_CAMPAIGN_SYNC"
queue = "ad-campaign-sync"

[[env.prod.queues.producers]]
binding = "AD_SETS_SYNC"
queue = "ad-sets-sync"

[[env.prod.queues.producers]]
binding = "AD_ADS_SYNC"
queue = "ad-ads-sync"


[[env.prod.queues.consumers]]
queue = "ad-account-sync"
max_batch_size = 1        # optional: defaults to 10
max_batch_timeout = 5     # optional: defaults to 5 seconds
max_concurrency = 6

[[env.prod.queues.consumers]]
queue = "ad-campaign-sync"
max_batch_size = 10        # optional: defaults to 10
max_batch_timeout = 5      # optional: defaults to 5 seconds
max_concurrency = 5
max_retries = 3

[[env.prod.queues.consumers]]
queue = "ad-sets-sync"
max_batch_size = 10    # optional: defaults to 10
max_batch_timeout = 5  # optional: defaults to 5 seconds
max_concurrency = 5
max_retries = 3

[[env.prod.queues.consumers]]
queue = "ad-ads-sync"
max_batch_size = 10   # optional: defaults to 10
max_batch_timeout = 5 # optional: defaults to 5 seconds
max_concurrency = 5
max_retries = 3
