// Generated by Wrangler by running `wrangler types src/types/worker-configuration.d.ts --env-interface WorkerEnv`

import { CounterDurable } from "~/durables/CounterDurable";
import { SubscriptionDurable } from "~/durables/SubscriptionDurable";
interface WorkerEnv {
	CACHING: KVNamespace;
	NODE_ENV: string;
	PORT: string;
	LAMBDA_SECRET_KEY: string;
	DIRECTUS_URL: string;
	DIRECTUS_SECRET_KEY: string;
	DIRECTUS_SERVICE_TOKEN: string;
	PORTAL_URL: string;
	AWS_ACCESS_KEY_ID: string;
	AWS_SECRET_ACCESS_KEY: string;
	OPENSEARCH_ENDPOINT: string;
	OPENSEARCH_USERNAME: string;
	OPENSEARCH_PASSWORD: string;
	STRIPE_API_KEY: string;
	STRIPE_WEBHOOK_SECRET: string;
	SUBSCRIPTION_DURABLE: DurableObjectNamespace<SubscriptionDurable>
	COUNTER_DURABLE: DurableObjectNamespace<CounterDurable>
}
