// Generated by Wrangler by running `wrangler types src/types/worker-configuration.d.ts --env-interface WorkerEnv`

interface WorkerEnv {
	CACHING: KVNamespace;
	NODE_ENV: string;
	PORT: string;
	LAMBDA_SECRET_KEY: string;
	DIRECTUS_URL: string;
	DIRECTUS_SECRET_KEY: string;
	DIRECTUS_SERVICE_TOKEN: string;
	PORTAL_URL: string;
	STRIPE_API_KEY: string;
	STRIPE_WEBHOOK_SECRET: string;
	STRIPE_WELCOME_COUPON: string;
	SUBSCRIPTION_DURABLE: DurableObjectNamespace /* SubscriptionDurable */;
	COUNTER_DURABLE: DurableObjectNamespace /* CounterDurable */;
	BILLING_QUEUE: Queue;
}
