name = "ums-api_dev"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

# [observability]
# enabled = true

routes = [
  { pattern = "portal-local.aiya.me/api/customer/*", zone_name = "aiya.me" },
  { pattern = "portal-dev.aiya.me/api/customer/*", zone_name = "aiya.me" },
  { pattern = "portal.aiya.me/api/customer/*", zone_name = "aiya.me" },
  { pattern = "lambda-api.aiya.me/api/customer/*", zone_name = "aiya.me" },
]

[placement]
mode = "smart"

[vars]
DIRECTUS_URL = "https://console.portal.aiya.ai"


[[kv_namespaces]]
binding = "CACHING"
id = "b494201ff6b74231a02c94891f805ba7"


[[durable_objects.bindings]]
name = "COUNTERS"
class_name = "MyDurableObject"

[[migrations]]
tag = "v1"                # Should be unique for each entry
new_sqlite_classes = ["MyDurableObject"]


# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
