name = "bot-api"
compatibility_date = "2024-08-21"
compatibility_flags = ["nodejs_compat"]


routes = [
  { pattern = "portal-local.aiya.me/api/bots/*", zone_name = "aiya.me" },
  { pattern = "portal-dev.aiya.me/api/bots/*", zone_name = "aiya.me" },
  { pattern = "portal.aiya.me/api/bots/*", zone_name = "aiya.me" },
  { pattern = "portal.aiya.me/api/aws/*", zone_name = "aiya.me" },
  { pattern = "lambda-api.aiya.me/api/bots/*", zone_name = "aiya.me" }, 
]

[placement]
mode = "smart"

[vars]
DIRECTUS_URL = "https://console.portal.aiya.ai"


[[vectorize]]
binding = "VECTOR_SENTENCES"
index_name = "sentences_embeddings"

[[queues.producers]]
binding = "SENTENCE_EMBEDINGS_QUEUE"
queue = "sentences-embeddings"

[[queues.consumers]]
queue = "sentences-embeddings"
max_batch_size = 10 # optional: defaults to 10
max_batch_timeout = 3 # optional: defaults to 5 seconds

[[kv_namespaces]]
binding = "CACHING"
id = "b494201ff6b74231a02c94891f805ba7"



# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
