// Generated by Wrangler by running `wrangler types src/types/worker-configuration.d.ts --env-interface WorkerEnv`

import { ChannelDurableObject } from "~/durables/channel.durable";

interface WorkerEnv {
	DIRECTUS_SECRET_KEY: string;
	PUBSUB_TOPIC: string;
	CHANNEL_API_URL: string;
	CHANNEL_DURABLE: DurableObjectNamespace<ChannelDurableObject>;
	CONTENT_BUCKET: R2Bucket;
	DB: D1Database;
	PUBSUB_API: Fetcher;
	CHANNEL_API: Fetcher;
	USER_PROFILE_QUEUE: Queue;
}
