// Generated by Wrangler by running `wrangler types src/types/worker-configuration.d.ts --env-interface WorkerEnv`

interface WorkerEnv {
	PUBSUB_API_URL: "http://localhost:14400";
	PUBSUB_TOPIC: "uws-api-dev";
	PUBSUB_API: Fetcher;
}
