name = "portal-api_dev"
compatibility_date = "2024-08-24"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "portal-dev.aiya.me/api/*", zone_name = "aiya.me" },
  { pattern = "liff-dev.aiya.me/api/files/*", zone_name = "aiya.me" }, 
  { pattern = "liff2-dev.aiya.me/api/files/*", zone_name = "aiya.me" },
]

[placement]
mode = "smart"

[[r2_buckets]]
binding = "BOT_MESSAGE_BUCKET"
bucket_name = "bot-message"
preview_bucket_name = "preview-bot-message"

[vars]
PORTAL_URL = "https://portal-dev.aiya.me"
FB_API_URL = "https://graph.facebook.com/v20.0"
FB_APP_ID = "788582819272015"
BOT_MESSAGE_BUCKET_CDN = "https://pub-07ce3c07d08e416caec26bf7a9128170.r2.dev"
LINE_WEBHOOK_ENDPOINT = "https://webhook-dev.aiya.me/api/v2/line/webhook"

[[kv_namespaces]]
binding = "CACHING"
id = "5e314082400b4a1dac3ec0a2937a8dd8"

[env.prod]
name = "portal-api_prod"

routes = [
  { pattern = "portal.aiya.me/api/*", zone_name = "aiya.me" },
  { pattern = "liff.aiya.me/api/files/*", zone_name = "aiya.me" }, 
  { pattern = "liff2.aiya.me/api/files/*", zone_name = "aiya.me" },
]

[env.prod.placement]
mode = "smart"

[env.prod.vars]
DIRECTUS_URL = "https://console.portal.aiya.ai"
PORTAL_URL = "https://portal.aiya.me"
FB_API_URL = "https://graph.facebook.com/v20.0"
FB_APP_ID = "788582819272015"
BOT_MESSAGE_BUCKET_CDN = "https://cdn-bot.aiya.me"
LINE_WEBHOOK_ENDPOINT = "https://webhook.aiya.me/api/v2/line/webhook"


[[env.prod.r2_buckets]]
binding = "BOT_MESSAGE_BUCKET"
bucket_name = "bot-message"


[[env.prod.kv_namespaces]]
binding = "CACHING"
id = "088f1972ae4347179a232a198ad780c0"