name = "billing-api_dev"
compatibility_date = "2024-08-21"
compatibility_flags = ["nodejs_compat"]

# Development environment
routes = [
  { pattern = "portal-dev.aiya.me/api/billing/*", zone_name = "aiya.me" },
]

[placement]
mode = "smart"

[vars]
DIRECTUS_URL = "https://console.portal.aiya.ai"

[[kv_namespaces]]
binding = "CACHING"
id = "b494201ff6b74231a02c94891f805ba7"


[durable_objects]
bindings = [
  { name = "SUBSCRIPTION_DURABLE", class_name = "SubscriptionDurable" },
  { class_name = "CounterDurable", name = "COUNTER_DURABLE" },
]

[[migrations]]
tag = "v1"
new_classes = ["SubscriptionDurable", "CounterDurable"]


# Production environment
[env.prod]
name = "billing-api_prod"

routes = [{ pattern = "portal.aiya.me/api/billing/*", zone_name = "aiya.me" }]

[env.prod.placement]
mode = "smart"

[env.prod.vars]
DIRECTUS_URL = "https://console.portal.aiya.ai"

[[env.prod.kv_namespaces]]
binding = "CACHING"
id = "b494201ff6b74231a02c94891f805ba7"


[env.prod.durable_objects]
bindings = [
  { name = "SUBSCRIPTION_DURABLE", class_name = "SubscriptionDurable" },
  { class_name = "CounterDurable", name = "COUNTER_DURABLE" },
]

[[env.prod.migrations]]
tag = "v1"
new_classes = ["SubscriptionDurable", "CounterDurable"]
