name = "proxy-line"
compatibility_date = "2024-08-24"
compatibility_flags = ["nodejs_compat"]


routes = [
]

[placement]
mode = "smart"

[vars]
PORTAL_URL = "https://portal-dev.aiya.me"
FB_API_URL = "https://graph.facebook.com/v20.0"
FB_APP_ID = "788582819272015"
FB_APP_LOGIN_ID = "764646715708204"



[env.prod]
name = "ad-api_prod"

routes = [
  { pattern = "portal.aiya.me/api/ads/*", zone_name = "aiya.me" },
  { pattern = "portal.aiya.me/api/adaccounts/*", zone_name = "aiya.me" },
]

[env.prod.placement]
mode = "smart"

[env.prod.vars]
PORTAL_URL = "https://portal.aiya.me"
FB_API_URL = "https://graph.facebook.com/v20.0"
FB_APP_ID = "788582819272015"
FB_APP_LOGIN_ID = "764646715708204"

