// Generated by Wrangler by running `wrangler types src/types/worker-configuration.d.ts --env-interface WorkerEnv`

interface WorkerEnv {
	CACHING: KVNamespace;
	SUPABASE_URL: "https://app-api.aiya.ai";
	SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhibHhpaHZjbnNrdHdqaWNzeXJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTMzMjg0ODksImV4cCI6MjAwODkwNDQ4OX0.MElXtyFRyjfyMlCNyqdf-iAI7xpPk0dCrzxH9Qe2RVY";
	NODE_ENV: string;
	PORT: string;
	LAMBDA_SECRET_KEY: string;
	DIRECTUS_URL: string;
	DIRECTUS_SECRET_KEY: string;
	DIRECTUS_SERVICE_TOKEN: string;
	PORTAL_URL: string;
	FB_APP_ID: string;
	FB_APP_SECRET: string;
	FB_APP_LOGIN_ID: string;
	AWS_ACCESS_KEY_ID: string;
	AWS_SECRET_ACCESS_KEY: string;
	OPENSEARCH_ENDPOINT: string;
	OPENSEARCH_USERNAME: string;
	OPENSEARCH_PASSWORD: string;
	SENTENCE_EMBEDINGS_QUEUE: Queue;
	VECTOR_SENTENCES: VectorizeIndex;
}
