// Generated by Wrangler by running `wrangler types src/types/worker-configuration.d.ts --env-interface WorkerEnv`

interface WorkerEnv {
	CACHING: KVNamespace;
	NODE_ENV: string;
	PORT: string;
	DIRECTUS_URL: string;
	DIRECTUS_SECRET_KEY: string;
	DIRECTUS_SERVICE_TOKEN: string;
	PORTAL_URL: string;
	FB_APP_ID: string;
	FB_APP_SECRET: string;
	FB_APP_LOGIN_ID: string;
	AWS_ACCESS_KEY_ID: string;
	AWS_SECRET_ACCESS_KEY: string;
	OPENSEARCH_ENDPOINT: string;
	OPENSEARCH_USERNAME: string;
	OPENSEARCH_PASSWORD: string;
	SUPABASE_URL: string;
	SUPABASE_ANON_KEY: string;
	OPENAI_API_KEY: string;
	GOOGLE_AI_PROJECT_ID: string;
	GOOGLE_AI_LOCATION_ID: string;
	GOOGLE_AI_API_ENDPOINT: string;
	GOOGLE_AI_MODEL_ID: string;
	GOOGLE_AI_GENERATE_CONTENT_API: string;
	GOOGLE_AI_ACCESS_TOKEN: string;
	BillingService: Fetcher;
	SENTENCE_EMBEDINGS_QUEUE: Queue;
	CAPI_QUEUE: Queue;
}
