name = "uws-api-dev"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["rpc"]

routes = [
  { pattern = "portal-dev.aiya.me/api/uws/*", zone_name = "aiya.me" },
  { pattern = "realtime-dev.aiya.me/api/uws/*", zone_name = "aiya.me" },
]

services = [
  # { binding = "PUBSUB_API", service = "pubsub-api-dev" },
  { binding = "CHANNEL_API", service = "channel-api-dev" },
]

[vars]
# PUBSUB_TOPIC = "uws-api-dev"
PORTAL_URL = "https://portal-dev.aiya.me"
# CHANNEL_API_URL = "http://localhost:14102/api"

[[r2_buckets]]
bucket_name = "uws"
binding = "CONTENT_BUCKET"

[[d1_databases]]
binding = "DB"
database_name = "uws"
database_id = "141a6f51-0b14-46eb-bb9c-fe9a1a0ed15b"

[[durable_objects.bindings]]
name = "CHANNEL_DURABLE"
class_name = "ChannelDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChannelDurableObject"]

[[queues.producers]]
queue = "user-profile-queue-dev"
binding = "USER_PROFILE_QUEUE"

[[queues.consumers]]
queue = "user-profile-queue-dev"
max_batch_size = 10
max_batch_timeout = 10

[[queues.producers]]
queue = "conversation-queue-dev"
binding = "CONVERSATION_QUEUE"

[[queues.consumers]]
queue = "conversation-queue-dev"
max_batch_size = 1
max_batch_timeout = 0


