name = "partner-api_dev"
compatibility_date = "2024-08-21"
compatibility_flags = ["nodejs_compat"]


routes = [
  { pattern = "liff-dev.aiya.me/api/partners/*", zone_name = "aiya.me" }, 
]

[placement]
mode = "smart"

[vars]
DIRECTUS_URL = "https://console.portal.aiya.ai"
QUEQ_URL = "http://api1.queq.me"
QUEQ_TOKEN = "eb6ed5f7013d4e9b858a22c0763e4bbe"

[[kv_namespaces]]
binding = "CACHING"
id = "b494201ff6b74231a02c94891f805ba7"



[env.prod]
name = "partner-api_prod"

routes = [
  { pattern = "liff.aiya.me/api/partners/*", zone_name = "aiya.me" }, 
]

[env.prod.placement]
mode = "smart"

[env.prod.vars]
DIRECTUS_URL = "https://console.portal.aiya.ai"
QUEQ_URL = "http://api1.queq.me"
QUEQ_TOKEN = "eb6ed5f7013d4e9b858a22c0763e4bbe"


[[env.prod.kv_namespaces]]
binding = "CACHING"
id = "b494201ff6b74231a02c94891f805ba7"
